config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/about/me', to: 'static_pages#about_me', as: 'about_me'
  get '/about/mon_groupe', to: 'static_pages#about_mon_groupe', as: 'about_group'
  get '/new', to: 'users#new', as: 'new_user'
  post'/new', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

end


#Pour chaque route on définit un path qui va nous permettre d'utiliser cette route plus facilement ailleurs

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :user_name, 
			uniqueness:true,
			format: { with: /\A[a-zA-Z0-9]+\Z/ }
end


#Conditions de validation qui permettent d'éviter que des Usernames puissent être enregistrés si 
#1) ils ne sont pas uniques
#2) ils contiennent un espace ou sont vides (REGEX)
#Ces validations permettent:
#1) d'éviter que ces Usernames ne soient enregistrés dans la Database via rails console: des Rollbacks apparaissent si on essaie
#2) d'empêcher l'enregistrement des Usernames sur le site, ce qui permet de renvoyer à une page d'erreur

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def about_me
  end

  def about_mon_groupe
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  	@user = User.create(user_name: params[:username], bio: params[:bio])
  	@user.user_name = params[:username]
  	@user.bio = params[:bio]
  	if @user.save
      redirect_to action: 'show', id: @user.user_name
      #redirect_to user_path(@user.user_name)
 	  else
      render '/users/erreur'
  	end
  end

  def show
  	@user = User.find_by(user_name: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

    <!-- Balise qui nous permet de rajouter un minimum de CSS. 
    On apprendra plus tard à utiliser bootstrap pour pimper nos sites rapidement. -->

    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1 align='center'>About ce site</h1>

<p> Ceci est un bon gros about des familles </p>

<p>Tu peux te rendre sur ma page personnelle en cliquant <a href="<%= about_me_path%>">ici</a> ! </p>

<p>Tu peux te rendre sur la page de la team courgette <a href="<%= about_group_path%>">ici</a> ! </p>


<!-- Ici, on fait appel à nos paths définis dans Routes.rb
On renvoie à nos deux supers pages About me et About my group.-->

app/views/static_pages/about_me.html.erb
<h1 align='center'>About me</h1>
<p>Je suis mousaillon chez thp, très souvent en pls mais on adore ça </p>

app/views/static_pages/about_mon_groupe.html.erb
<h1 align='center'>About mon groupe : La team rennes </h1>
<p>Je fais parti de la team rennaise composée de Sandrine, Léona, Christophe, Rémi et moi même, Romain ! </p>

app/views/static_pages/contact.html.erb
<h1 align='center'>Contact</h1>
<p>Salut la jeunesse, si vous voulez de infos sur THP ou des hacks sur les projets à venir, vous pouvez contacter Charles, co-fondateur de The Hacking Project pourra répondre à toutes vos questions : 06.95.46.60.80</p>

app/views/static_pages/home.html.erb
<h1 align='center'>Bienvenue sur ma page d'accueil</h1>
<p>Bienvenue à toi jeune moussaillon </p>

<p>Pour créer un utilisateur c'est par <a href="<%= new_user_path%>">ici </a></p>
<br>

<p>Pour la première partie de l'exo tu peux aller voir ici mon about pour voir que ça marche <a href="<%=about_path%>"> (clique ici)</a></p>

app/views/users/erreur.html.erb
<h1>Too bad, welcome sur la page des loosers : la page erreur..</h1>

<p>
  Cet Username est déjà prit
</p>

app/views/users/new.html.erb
<h1>Bienvenue dans la création d'utilisateurs ! </h1>

<p>On crée ici un nouvel utilisateur</p>

 <form action="/new" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
   Username: <br>
  <input type="text" name="username"><br>
  <br>
   Bio: <br>
  <textarea name="bio">Entre ton texte ici...</textarea>
  <br>
  <input type="submit" value="Submit">
</form>




<!-- Ici, on crée un formulaire qui va demander à l'utilisateur son Nom et sa Bio.
On stocke ces infos grâce aux variables username et bio de notre formulaire.
"action" nous permet de signifier la page où l'on trouve le formulaire.
On utilise la méthode POST car on veut stocker nos informations et les mettre à jour dans notre modèle User. -->

app/views/users/show.html.erb
<h1> Bienvenue <%= @user.user_name %></h1>

<p>Voici ta belle bio des familles : <%= @user.bio %> </p>



<!-- Ici, pour chaque utilisateur qui rentre son nom et sa bio, on va lui afficher ses informations sur sa page User personnalisée. -->